name: CI for PlanV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Skip react-native-reanimated in Podfile
      run: |
        cd PlanVapp/ios
        sed -i.bak '/react-native-reanimated/d' Podfile

    - name: Skip RNFBAnalytics in Podfile (CI only)
      run: |
        cd PlanVapp/ios
        sed -i.bak '/@react-native-firebase\/analytics/d' Podfile

    - name: Install Dependencies
      run: npm install

    - name: Install CocoaPods
      run: |
        cd PlanVapp/ios
        pod install

    - name: Build with Metro
      run: npm run build

    - name: Build with Xcode
      run: |
        cd PlanVapp/ios
        xcodebuild -workspace PlanV.xcworkspace \
          -scheme PlanV \
          -configuration Release \
          -derivedDataPath build

    - name: Run Jest Tests
      run: npm test
