name: CI for PlanV
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Dependencies
      run: |
        cd PlanVapp
        npm install
    - name: Run Tests
      run: |
        cd PlanVapp
        npm test
