name: CI for PlanV
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Dependencies
      run: |
        cd PlanVapp
        npm install
        npm install @react-native-async-storage/async-storage react-native-credit-card @react-native-community/geolocation react-native-maps react-native-google-places-autocomplete
    - name: Build with Metro
      run: |
        cd PlanVapp
        npx react-native bundle --entry-file index.js --platform ios --dev false --bundle-output ios/main.jsbundle --assets-dest ios
    - name: Run Tests
      run: |
        cd PlanVapp
        npm test
